'use client';
import { readApiJson } from '@/lib/api-json';
import { useEffect, useState } from 'react';
export default function AlashiPriceRange({rangeId,label}:{rangeId:string;label:string}) {
  const [floor,setFloor]=useState('');const [min,setMin]=useState('');const [max,setMax]=useState('');const [notice,setNotice]=useState('');const [busy,setBusy]=useState(false);
  useEffect(()=>{let active=true;setMin('');setMax('');setFloor('');setNotice('');fetch('/api/admin/alashi/').then(async r=>{const data=await readApiJson(r);if(!r.ok)throw new Error(data.error);if(active){const range=data.records.find((r:{id:string})=>r.id===rangeId)?.value;setMin(range?String(range.min):'');setMax(range?String(range.max):'');setFloor(range?.floor!==undefined?String(range.floor):'');}}).catch(e=>{if(active)setNotice(e.message);});return()=>{active=false;};},[rangeId]);
  async function save(){setBusy(true);setNotice('');try{const response=await fetch('/api/admin/alashi/',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'range',id:rangeId,range:!min&&!max?null:{min:min?Number(min):null,max:max?Number(max):null,...(floor?{floor:Number(floor)}:{})}})});const data=await readApiJson(response);if(!response.ok)throw new Error(data.error);setNotice('AI range saved.');}catch(e){setNotice(e instanceof Error?e.message:'Could not save.');}finally{setBusy(false);}}
  return <fieldset className="border border-emerald-400/20 rounded-xl p-4 my-3"><legend className="text-sm text-emerald-200 px-2">ALASHI price range · {label}</legend><div className="flex flex-wrap gap-3 items-end"><label className="text-xs text-white/70">Minimum (£)<input type="number" min="0.01" step="0.01" value={min} onChange={e=>setMin(e.target.value)} className="admin-input block mt-2 w-36"/></label><label className="text-xs text-white/70">Maximum (£)<input type="number" min="0.01" step="0.01" value={max} onChange={e=>setMax(e.target.value)} className="admin-input block mt-2 w-36"/></label><label className="text-xs text-white/70">Private lowest offer (£)<input type="number" min="0.01" step="0.01" value={floor} onChange={e=>setFloor(e.target.value)} className="admin-input block mt-2 w-36" placeholder="No negotiation"/></label><button type="button" onClick={save} disabled={busy} className="bg-emerald-700 text-white rounded-lg px-4 py-3 text-xs">{busy?'Saving…':'Save AI range'}</button></div><p className="text-xs text-white/50 mt-3">Saved separately from the selling price. The private lowest offer is never sent to the customer or AI provider. The product selling price is the listed price. Negotiation moves halfway toward your private floor, then reaches it only after repeated requests. Leave the floor empty to keep a fixed price.</p>{notice&&<p role="status" className="text-sm text-emerald-200 mt-2">{notice}</p>}</fieldset>;
}
