'use client';
import { readApiJson } from '@/lib/api-json';
import { useCallback, useEffect, useState } from 'react';
import { SOFA_CATEGORIES } from '@/lib/product-categories';
import type { AlashiRecord, Knowledge, Question } from '@/lib/alashi-store';
import AlashiBusinessSettings from '@/components/AlashiBusinessSettings';
import AlashiChat from '@/components/AlashiChat';
import AlashiPriceRange from '@/components/AlashiPriceRange';
export default function AlashiAdmin(){
  const [data,setData]=useState<AlashiRecord[]>([]);const [connected,setConnected]=useState(false);const [notice,setNotice]=useState('');
  const [title,setTitle]=useState('');const [text,setText]=useState('');const [editId,setEditId]=useState<string>();const [questionId,setQuestionId]=useState<string>();const [busy,setBusy]=useState(false);
  const load=useCallback(async()=>{try{const r=await fetch('/api/admin/alashi/');const d=await readApiJson(r);if(!r.ok)throw new Error(d.error);setData(d.records);setConnected(d.connected);}catch(e){setNotice(e instanceof Error?e.message:'Could not load ALASHI.');}},[]);
  useEffect(()=>{load();},[load]);
  async function mutate(body:object){setBusy(true);setNotice('');try{const r=await fetch('/api/admin/alashi/',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await readApiJson(r);if(!r.ok)throw new Error(d.error);await load();setNotice('Saved. ALASHI will use your approved knowledge on the next message.');return true;}catch(e){setNotice(e instanceof Error?e.message:'Save failed.');return false;}finally{setBusy(false);}}
  return <div className="text-white/90 max-w-5xl"><h1 className="text-3xl mb-2">ALASHI</h1><p className="text-white/60 mb-6">Your sofa assistant · knowledge, owner inbox and pricing</p><div className="admin-card p-5 mb-6"><strong>{connected?'AI connection configured':'AI connection needs setup'}</strong><p className="text-sm text-white/60 mt-2">{connected?'Chat, photo analysis and custom image generation use your server API key.':'Add OPENAI_API_KEY to the server environment and restart. Catalogue search, policy answers and the owner inbox work while AI is disconnected.'}</p><p className="text-sm text-white/60 mt-2">Knowledge updates take effect immediately. Customer messages never train the model or change your rules automatically. English replies, Cash on Delivery, postcode delivery and private negotiation limits follow your latest rules. Listed catalogue prices are used if no custom range is configured.</p></div>
      {notice&&<p role="status" className="p-4 mb-5 bg-emerald-900/40 rounded-xl">{notice}</p>}
      <AlashiBusinessSettings /><AlashiChat /><section className="admin-card p-5 mb-6"><h2 className="text-xl mb-4">Questions needing your answer</h2><button onClick={load} className="text-sm underline mb-3">Refresh inbox</button>{!data.some(r=>r.kind==='question'&&!(r.value as Question).answer)&&<p className="text-white/50 text-sm">No unanswered questions.</p>}{data.filter(r=>r.kind==='question'&&!(r.value as Question).answer).map(r=><article key={r.id} className="border-t border-white/10 py-4"><p>{(r.value as Question).text}</p><small className="text-white/40">{new Date((r.value as Question).created).toLocaleString()}</small><div className="flex gap-4 mt-2"><button onClick={()=>{setQuestionId(r.id);setEditId(undefined);setTitle((r.value as Question).text);setText('');document.getElementById('alashi-knowledge')?.scrollIntoView({behavior:'smooth'});}} className="text-emerald-300">Answer and teach ALASHI</button><button disabled={busy} onClick={()=>mutate({action:'delete',id:r.id})} className="text-white/40">Dismiss</button></div></article>)}</section>
      <form id="alashi-knowledge" className="admin-card p-5 mb-6" onSubmit={async e=>{e.preventDefault();if(await mutate({action:questionId?'answer':'knowledge',id:questionId||editId,title,text})){setTitle('');setText('');setQuestionId(undefined);setEditId(undefined);}}}><h2 className="text-xl mb-4">{questionId?'Approve an answer':editId?'Edit knowledge':'Add business knowledge'}</h2><label className="block mb-4 text-sm">Question or document title<input required maxLength={3000} value={title} onChange={e=>setTitle(e.target.value)} className="admin-input w-full mt-2"/></label><label className="block text-sm">Approved answer / business information<textarea required maxLength={30000} rows={8} value={text} onChange={e=>setText(e.target.value)} className="admin-input w-full mt-2"/></label><label className="block text-sm my-4">Import a knowledge document (TXT, MD or CSV)<input type="file" accept=".txt,.md,.csv" className="block mt-2" onChange={async e=>{const f=e.target.files?.[0];if(!f)return;if(f.size>100000){setNotice('Keep knowledge documents below 100 KB.');return;}setTitle(f.name);setText((await f.text()).slice(0,30000));setEditId(undefined);setQuestionId(undefined);e.target.value='';}}/></label><p className="text-xs text-white/50 mb-4">Review imported content before approving. Include only customer-facing facts; do not add passwords, private margins or customer personal data.</p><button disabled={busy} className="bg-emerald-700 px-5 py-3 rounded-xl">Approve and save knowledge</button></form>
      <section className="admin-card p-5 mb-6"><h2 className="text-xl mb-4">Approved knowledge</h2>{data.filter(r=>r.kind==='knowledge').map(r=><article key={r.id} className="border-t border-white/10 py-4"><strong>{(r.value as Knowledge).title}</strong><p className="text-sm text-white/60 whitespace-pre-wrap my-2">{(r.value as Knowledge).text}</p><button className="text-emerald-300 mr-5" onClick={()=>{setTitle((r.value as Knowledge).title);setText((r.value as Knowledge).text);setEditId(r.id);setQuestionId(undefined);document.getElementById('alashi-knowledge')?.scrollIntoView({behavior:'smooth'});}}>Edit</button><button className="text-white/40" disabled={busy} onClick={()=>mutate({action:'delete',id:r.id})}>Remove</button></article>)}</section>
      <section className="admin-card p-5"><h2 className="text-xl mb-2">Category price ranges</h2><p className="text-sm text-white/50 mb-4">All six categories. Product-specific ranges in Products override these defaults. ALASHI never invents a missing range.</p>{SOFA_CATEGORIES.map(c=><AlashiPriceRange key={c} rangeId={`category:${c}`} label={c}/>)}</section>
    </div>;
}
