 'use client';
import { useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';
import { ArrowRight, Palette } from 'lucide-react';
import { useCart } from '@/context/CartContext';
import FabricChoices from '@/components/sofa-builder/FabricChoices';
import type { FabricSwatch } from '@/lib/fabric-options';
export default function SwatchesPage(){
 const [fabrics,setFabrics]=useState<FabricSwatch[]>([]),[selected,setSelected]=useState(''),[error,setError]=useState(''),[loading,setLoading]=useState(true),[target,setTarget]=useState('');
 const {items}=useCart();const router=useRouter();const sofas=items.filter(i=>i.itemType!=='swatch');
 useEffect(()=>{const load=()=>fetch('/api/swatches/',{cache:'no-store'}).then(async r=>{const data=await r.json();if(!r.ok)throw new Error(data.error);setFabrics(data);setError('');}).catch(e=>setError(e.message)).finally(()=>setLoading(false));load();window.addEventListener('focus',load);return()=>window.removeEventListener('focus',load);},[]);
 function continueToSofa(){const item=sofas.find(i=>i.variantId===target);const params=new URLSearchParams({fabric:selected});if(item){if(item.buildId){params.set('build',item.buildId);params.set('edit',item.variantId);}else{params.set('product',item.productId);params.set('variant',item.variantId);params.set('edit',item.variantId);}}router.push(`/build/?${params}`);}
 return <div className="fabric-library commerce-studio"><header className="fabric-library-hero"><span className="studio-eyebrow"><Palette size={17}/>THE FINISHING TOUCH</span><h1>A texture to love.<br/><em>A sofa made yours.</em></h1><p>Explore fabrics, choose your favourite, then pair it with your sofa. Your fabric becomes part of the sofa order.</p></header><main className="fabric-library-content">{error&&<p role="alert" className="fabric-error">{error}</p>}{loading?<p role="status">Loading the fabric collection...</p>:<>{Array.from(new Set(fabrics.map(f=>f.material))).map(material=><section key={material}><h2>{material}</h2><FabricChoices swatches={fabrics.filter(f=>f.material===material)} value={selected} onChange={setSelected}/></section>)}<p>Fabric images appear where available. Plain tiles are colour references; screen colours may vary.</p><section className="fabric-next"><div><h2>{selected?'Now choose its sofa.':'Found your favourite?'}</h2><p>{fabrics.find(f=>f.id===selected)?.name||'Choose a fabric above to continue.'} {selected&&'will be saved as your sofa fabric choice.'}</p></div>{sofas.length>0&&<label>Apply to<select value={target} onChange={e=>setTarget(e.target.value)}><option value="">Choose a new sofa</option>{sofas.map(i=><option key={i.variantId} value={i.variantId}>{i.title} - {i.color}</option>)}</select></label>}<button disabled={!selected} onClick={continueToSofa}>{target?'Customise this sofa':'Choose my sofa'}<ArrowRight size={18}/></button></section></>}</main></div>;
}
