'use client';
import { useEffect, useState } from 'react';
import type { FabricSwatch } from '@/lib/fabric-options';
const empty:FabricSwatch={id:'',name:'',material:'',hex_color:'#64715c',image_url:null,surchargePence:0};
export default function FabricAdmin(){
 const [list,setList]=useState<FabricSwatch[]>([]),[form,setForm]=useState(empty),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 async function load(){const r=await fetch('/api/swatches/');if(!r.ok)throw new Error('Could not load fabrics');setList(await r.json());}
 useEffect(()=>{load().catch(e=>setMessage(e.message));},[]);
 async function upload(file?:File){if(!file)return;setBusy(true);try{const r=await fetch('/api/product-images/',{method:'POST',body:file});const data=await r.json();if(!r.ok)throw new Error(data.error);setForm(current=>({...current,image_url:data.url}));setMessage('Photograph uploaded. Save fabric to publish it.');}catch(e){setMessage(e instanceof Error?e.message:'Upload failed');}finally{setBusy(false);}}
 async function save(e:React.FormEvent){e.preventDefault();setBusy(true);try{const r=await fetch('/api/swatches/',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)});const data=await r.json();if(!r.ok)throw new Error(data.error);await load();setForm(empty);setMessage('Fabric published to Swatches and the sofa builder.');}catch(e){setMessage(e instanceof Error?e.message:'Save failed');}finally{setBusy(false);}}
 return <section className="admin-card space-y-4 p-6"><h2 className="text-lg">Fabric &amp; swatch collection</h2><p className="text-sm text-white/60">One catalogue for the Swatches page and builder. Fabric is part of the sofa, with no separate basket product. A zero surcharge means included.</p><select className="admin-input w-full" value={form.id} onChange={e=>setForm(list.find(s=>s.id===e.target.value)||empty)}><option value="">Add a new fabric</option>{list.map(s=><option key={s.id} value={s.id}>{s.material} · {s.name}</option>)}</select><form onSubmit={save} className="grid gap-4 sm:grid-cols-2"><label>Name<input required className="admin-input mt-2 w-full" maxLength={120} value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Material<input required className="admin-input mt-2 w-full" maxLength={80} value={form.material} onChange={e=>setForm({...form,material:e.target.value})}/></label><label>Colour<input type="color" className="mt-2 block h-12 w-full" value={form.hex_color} onChange={e=>setForm({...form,hex_color:e.target.value})}/></label><label>Surcharge (£)<input type="number" min={0} step="0.01" required className="admin-input mt-2 w-full" value={(form.surchargePence||0)/100} onChange={e=>setForm({...form,surchargePence:Math.round(Number(e.target.value)*100)})}/></label><label>Fabric photograph<input type="file" accept="image/jpeg,image/png,image/webp" disabled={busy} className="mt-2 block text-sm" onChange={e=>void upload(e.target.files?.[0])}/></label>{form.image_url&&<img src={form.image_url} alt="Fabric preview" className="h-24 w-24 rounded-lg object-cover"/>}<button disabled={busy} className="rounded-xl bg-emerald-700 px-5 py-3 sm:col-span-2">{busy?'Saving…':'Save fabric'}</button></form>{message&&<p role="status" className="text-sm text-amber-200">{message}</p>}</section>;
}
